#!/usr/bin/env ruby
require './app'

def options
  puts '                                     '
  puts 'Please choose an option by enterin a corresponding number'
  puts ' 1 - List all books'
  puts ' 2 - List all people'
  puts ' 3 - Create a person'
  puts ' 4 - Create a book'
  puts ' 5 - Create a rental'
  puts ' 6 - List all rentals for a given person id'
  puts ' 7 - Exit the application'
  puts '          '
end

def response(app, input)
  case input
  when 1
    app.all_books
  when 2
    app.all_people
  when 3
    app.person_select
  when 4
    app.create_book
  when 5
    app.add_rentals
  when 6
    app.list_rentals
  end
end

def main
  puts 'Welcome to the School Library'
  app = App.new
  input = 0
  while input != 7
    options
    input = gets.chomp
    input = input.to_i
    response(app, input)
  end
  puts 'Thanks for using Swave School library App'
end

main
