#!/usr/bin/env ruby
require './app'

puts "Welcome to the School Library"
def starter                                                     
 puts  "                             "
 puts "Please choose an option by enterin a corresponding number"
 puts " 1 - List all books" 
 puts " 2 - List all people"
 puts " 3 - Create a person" 
 puts " 4 - Create a book"
 puts " 5 - Create a rental"
 puts " 6 - List all rentals for a given person id"
 puts " 7 - Exit the application"  
 puts "                                             "
 input = gets.chomp
 input = input.to_i
 app = App.new()

  case input
   when 1
    app.all_books
    starter()
   when 2
    app.all_people
    starter()
   when 3
     puts  "Do you want to create a (1) student or a (2) teacher: "
     personInput = gets.chomp
     personInput = personInput.to_i
       case personInput
         when 1
          app.create_student
         when 2
          app.create_teacher
       end
   starter()
   when 4
    app.create_book
    starter()
   when 5
    app.add_rentals
    starter()
   when 6
   app.list_rentals
   starter()
   when 7
     puts 'Thanks for using our application. Please do well to visit again'
   end
end

def main
 starter()
end

main()
  
